var json = {
	"tool1": {
		"name": ["Name:", "Drill Press"],
		"groups": ["Tool/Item Type:", "Power Tool"],
		"make": ["Make", "Delta"],
		"mnumber": ["Model Number:", "11-550"],
		"snumber": ["Serial Number:", "12345677"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Lowes"],
		"price": ["Price:", "$199.99"],
		"ev": ["Estimated Value:", "$199.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	},
	"tool2": {
		"name": ["Name:", "Wrench"],
		"groups": ["Tool/Item Type:", "Hand Tool"],
		"make": ["Make", "Craftsman"],
		"mnumber": ["Model Number:", "wr789"],
		"snumber": ["Serial Number:", "erfdwws"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Sears"],
		"price": ["Price:", "$19.99"],
		"ev": ["Estimated Value:", "$19.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	},
	"tool3": {
		"name": ["Name:", "Miter Saw"],
		"groups": ["Tool/Item Type:", "Power Tool"],
		"make": ["Make", "Makita"],
		"mnumber": ["Model Number:", "LS1214"],
		"snumber": ["Serial Number:", "ls12141113"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Lowes"],
		"price": ["Price:", "$399.99"],
		"ev": ["Estimated Value:", "$399.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", ""]
	},
	"tool4": {
		"name": ["Name:", "Router Template Guide Set"],
		"groups": ["Tool/Item Type:", "Power Tool Accessory"],
		"make": ["Make", "Porter Cable"],
		"mnumber": ["Model Number:", "42000"],
		"snumber": ["Serial Number:", "4200"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Sears"],
		"price": ["Price:", "$19.99"],
		"ev": ["Estimated Value:", "$19.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "9-piece set"]
	},
	"tool5": {
		"name": ["Name:", "Edge Guide"],
		"groups": ["Tool/Item Type:", "Power Tool Accessory"],
		"make": ["Make", "Porter Cable"],
		"mnumber": ["Model Number:", "42690"],
		"snumber": ["Serial Number:", "42690"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "ebay"],
		"price": ["Price:", "$14.99"],
		"ev": ["Estimated Value:", "$19.99"],
		"condition": ["Purchase Type:", "Used"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	},
	"tool6": {
		"name": ["Name:", "Biscuit Joiner"],
		"groups": ["Tool/Item Type:", "Power Tool"],
		"make": ["Make", "Porter Cable"],
		"mnumber": ["Model Number:", "557"],
		"snumber": ["Serial Number:", "557"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "amazon.com"],
		"price": ["Price:", "$199.99"],
		"ev": ["Estimated Value:", "$199.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	},
	"tool7": {
		"name": ["Name:", "Router Kit"],
		"groups": ["Tool/Item Type:", "Power Tool"],
		"make": ["Make", "Porter Cable"],
		"mnumber": ["Model Number:", "895PK"],
		"snumber": ["Serial Number:", "895PK"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Home Depot"],
		"price": ["Price:", "$199.99"],
		"ev": ["Estimated Value:", "$199.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "Includes Router Motor, Fixed Base, Plunge Base, Height adjuster, 1/4 & 1/2 collets, Sub-Base Centering Gauge, Collet wrench, Carrying case"]
	},
	"tool8": {
		"name": ["Name:", "Hard Maple"],
		"groups": ["Tool/Item Type:", "Lumber"],
		"make": ["Make", "na"],
		"mnumber": ["Model Number:", "na"],
		"snumber": ["Serial Number:", "na"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodcraft"],
		"price": ["Price:", "$49.99"],
		"ev": ["Estimated Value:", "$49.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "3"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "10 b.f."]
	},
	"tool9": {
		"name": ["Name:", "Birdseye Maple"],
		"groups": ["Tool/Item Type:", "Lumber"],
		"make": ["Make", "na"],
		"mnumber": ["Model Number:", "na"],
		"snumber": ["Serial Number:", "na"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodcraft"],
		"price": ["Price:", "$69.99"],
		"ev": ["Estimated Value:", "$69.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "3"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "10 b.f."]
	},
	"tool10": {
		"name": ["Name:", "Mahogany"],
		"groups": ["Tool/Item Type:", "Lumber"],
		"make": ["Make", "na"],
		"mnumber": ["Model Number:", "na"],
		"snumber": ["Serial Number:", "na"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodcraft"],
		"price": ["Price:", "$39.99"],
		"ev": ["Estimated Value:", "$39.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "3"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "5 b.f."]
	},
	"tool11": {
		"name": ["Name:", "5 HP Motor 10 in. UNISAW with 52 in. BIESEMEYER Fence System"],
		"groups": ["Tool/Item Type:", "Power Tool"],
		"make": ["Make", "Delta"],
		"mnumber": ["Model Number:", "36-L552"],
		"snumber": ["Serial Number:", "12345677"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Lowes"],
		"price": ["Price:", "$899.99"],
		"ev": ["Estimated Value:", "$899.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	},
	"tool12": {
		"name": ["Name:", "14 in. 1 HP Steel Frame Band Saw"],
		"groups": ["Tool/Item Type:", "Power Tool"],
		"make": ["Make", "Delta"],
		"mnumber": ["Model Number:", "28-400"],
		"snumber": ["Serial Number:", "erfdwws"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodcraft"],
		"price": ["Price:", "$299.99"],
		"ev": ["Estimated Value:", "$299.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	},
	"tool13": {
		"name": ["Name:", "13 in. Portable Thickness Planer"],
		"groups": ["Tool/Item Type:", "Power Tool"],
		"make": ["Make", "Delta"],
		"mnumber": ["Model Number:", "22-590"],
		"snumber": ["Serial Number:", "ls12141113"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Lowes"],
		"price": ["Price:", "$199.99"],
		"ev": ["Estimated Value:", "$199.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", ""]
	},
	"tool14": {
		"name": ["Name:", "1 1/2 HP Motor Single Stage 1 Micron Dust Collector"],
		"groups": ["Tool/Item Type:", "Power Tool"],
		"make": ["Make", "Porter Cable"],
		"mnumber": ["Model Number:", "50-786"],
		"snumber": ["Serial Number:", "4200"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodcraft"],
		"price": ["Price:", "$199.99"],
		"ev": ["Estimated Value:", "$199.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", ""]
	},
	"tool15": {
		"name": ["Name:", "SPAX General Woodworking Screw Assortment"],
		"groups": ["Tool/Item Type:", "Hardware"],
		"make": ["Make", "Spax"],
		"mnumber": ["Model Number:", "Spax-1"],
		"snumber": ["Serial Number:", "na"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "McFeely's.com"],
		"price": ["Price:", "$19.99"],
		"ev": ["Estimated Value:", "$19.99"],
		"condition": ["Purchase Type:", "new"],
		"qty": ["Quantity:", "75"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "#2"]
	},
	"tool16": {
		"name": ["Name:", "#8 Black Oxide Plated Flat Head Screw Assortment"],
		"groups": ["Tool/Item Type:", "Hardware"],
		"make": ["Make", "McFeely's"],
		"mnumber": ["Model Number:", "0800-FSK"],
		"snumber": ["Serial Number:", "0800-FSK"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "McFeely's.com"],
		"price": ["Price:", "$19.99"],
		"ev": ["Estimated Value:", "$19.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "Black Oxide"]
	},
	"tool17": {
		"name": ["Name:", "INCRA LS Positioner Super System"],
		"groups": ["Tool/Item Type:", "Power Tool Accessory"],
		"make": ["Make", "Incra"],
		"mnumber": ["Model Number:", "LS25WFNCSYS"],
		"snumber": ["Serial Number:", "LS25WFNCSYS"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodpeckers.com"],
		"price": ["Price:", "$499.99"],
		"ev": ["Estimated Value:", "$499.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "1"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", ""]
	},
	"tool18": {
		"name": ["Name:", "Oak"],
		"groups": ["Tool/Item Type:", "Lumber"],
		"make": ["Make", "na"],
		"mnumber": ["Model Number:", "na"],
		"snumber": ["Serial Number:", "na"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodcraft"],
		"price": ["Price:", "$49.99"],
		"ev": ["Estimated Value:", "$49.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "5"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	},
	"tool19": {
		"name": ["Name:", "Quilted Maple"],
		"groups": ["Tool/Item Type:", "Lumber"],
		"make": ["Make", "na"],
		"mnumber": ["Model Number:", "na"],
		"snumber": ["Serial Number:", "na"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodcraft"],
		"price": ["Price:", "$69.99"],
		"ev": ["Estimated Value:", "$69.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "4"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	},
	"tool20": {
		"name": ["Name:", "Bubinga"],
		"groups": ["Tool/Item Type:", "Lumber"],
		"make": ["Make", "na"],
		"mnumber": ["Model Number:", "na"],
		"snumber": ["Serial Number:", "na"],
		"dpurchased": ["Date Purchased:", "2012-7-24"],
		"wpurchased": ["Where Purchased:", "Woodcraft"],
		"price": ["Price:", "$99.99"],
		"ev": ["Estimated Value:", "$99.99"],
		"condition": ["Purchase Type:", "New"],
		"qty": ["Quantity:", "6"],
		"dateadded": ["Date Added:", "2012-7-24"],
		"notes": ["Additional Notes:", "nse"]
	}
}